export const routes = {
  DEFAULT: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOTPASSWORD: '/forgotPassword',
  RESETPASSWORD: '/resetPassword/:token',
  HOME: '/discover',
  MEET: '/meet',
  // MESSAGES: '/messages',
  MYPROJECTS: '/myProjects',
  PROFILE: '/profile',
  PROJECT: '/project',
  NEWPROJECT: '/newProject',
  // PROJECTPOST: '/projectPost',
  CREATEPROJECT: '/createProject',
  ACCEPTINVITATION: '/projects/:projectId/members/:roleId/invite',
  // MESSAGEHISTORY: '/messageHistory',
  DISCOVERANDMEET: '/discoverAndMeet',
  SETTINGS: '/settings',
  CREDITS: '/credits',
  ABOUT: '/about',
  ACCOUNTACTIVATE: '/activation/:token',
  NOTFOUND: '/*',
};
