export const routes = {
  DEFAULT: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOTPASSWORD: '/forgotPassword',
  RESETPASSWORD: '/resetPassword/:token',
  HOME: '/projects',
  MEET: '/people',
  // MESSAGES: '/messages',
  MYPROJECTS: '/myProjects',
  PROFILE: '/profile',
  PROJECT: '/project',
  NEWPROJECT: '/newProject',
  // PROJECTPOST: '/projectPost',
  CREATEPROJECT: '/createProject',
  ACCEPTINVITATION: '/acceptInvite/:requestId',
  ACCEPTAPPLICATION: '/acceptApplication/:requestId',
  // MESSAGEHISTORY: '/messageHistory',
  DISCOVERANDMEET: '/discoverAndMeet',
  SETTINGS: '/settings',
  CREDITS: '/credits',
  ABOUT: '/about',
  ACCOUNTACTIVATE: '/activation/:token',
  NOTFOUND: '/*',
};
