openapi: 3.0.3
info:
  title: Looking For Group API
  version: 1.0.0
  description: |
    LFG API Documentation. This will showcase all the endpoints available and how to use them.
    Note: When accessed directly from the express app, the endpoints will have an additional "/api" prefix.
    Because of this, please use the vite proxy when reviewing the docs.
paths:
  # ADMIN
  /api/admin/promote:
    $ref: './paths/admin/promote.yaml'
  /api/admin/demote:
    $ref: './paths/admin/demote.yaml'
  /api/admin/tags:
    $ref: './paths/admin/tags.yaml'
  /api/admin/tags/{id}:
    $ref: './paths/admin/tags-id.yaml'
  /api/admin/skills:
    $ref: './paths/admin/skills.yaml'
  /api/admin/skills/{id}:
    $ref: './paths/admin/skills-id.yaml'
  /api/admin/status/{id}:
    $ref: './paths/admin/status.yaml'

  # DATASETS
  /api/datasets/majors/:
    $ref: './paths/datasets/majors.yaml'
  /api/datasets/mediums/:
    $ref: './paths/datasets/mediums.yaml'
  /api/datasets/roles/:
    $ref: './paths/datasets/roles.yaml'
  /api/datasets/skills/:
    $ref: './paths/datasets/skills.yaml'
  /api/datasets/socials/:
    $ref: './paths/datasets/socials.yaml'
  /api/datasets/tags/:
    $ref: './paths/datasets/tags.yaml'

  # IMAGES
  /api/images/{image}::
    $ref: './paths/images.yaml'

  # ME
  /api/me:
    $ref: './paths/me/me.yaml'
  /api/me/get-username:
    $ref: './paths/me/get-username.yaml'
  /api/me/projects:
    $ref: './paths/me/projects.yaml'
  /api/me/projects/{id}/leave:
    $ref: './paths/me/leave-proj.yaml'
  /api/me/projects/{id}/visibility:
    $ref: './paths/me/proj-visibility.yaml'
  /api/me/tag-blacklist:
    $ref: './paths/me/tag-blacklist.yaml'
  /api/me/blocklist:
    $ref: './paths/me/blocklist.yaml'
  /api/me/notifications/{id}/read:
    $ref: './paths/me/notification-read.yaml'
  /api/me/socials:
    $ref: './paths/me/socials.yaml'
  /api/me/socials/{id}:
    $ref: './paths/me/socials-id.yaml'
  /api/me/majors:
    $ref: './paths/me/majors.yaml'
  /api/me/majors/{id}:
    $ref: './paths/me/majors-id.yaml'
  /api/me/skills:
    $ref: './paths/me/skills.yaml'
  /api/me/skills/{id}:
    $ref: './paths/me/skills-id.yaml'

  # FOLLOWINGS
  /api/me/followings/people/{id}:
    $ref: './paths/me/followings/follow-proj.yaml'
  /api/me/followings/projects/{id}:
    $ref: './paths/me/followings/follow-user.yaml'

  # REPORTS
  /api/me/report-bug:
    $ref: './paths/me/reports/report-bug.yaml'
  /api/me/users/report/{id}:
    $ref: './paths/me/reports/report-user.yaml'
  /api/me/projects/report/{id}:
    $ref: './paths/me/reports/report-project.yaml'

  # GALLERY
  /api/me/gallery/{userId}/images:
    $ref: './paths/me/gallery/images.yaml'
  /api/me/gallery/{userId}/images/{imageId}:
    $ref: './paths/me/gallery/image-id.yaml'
  /api/me/gallery/{userId}/videos:
    $ref: './paths/me/gallery/videos.yaml'
  /api/me/gallery/{userId}/videos/{videoId}:
    $ref: './paths/me/gallery/video-id.yaml'

  # MOD
  /api/mod/user-report/{id}:
    $ref: './paths/mod/user-report.yaml'
  /api/mod/project-report/{id}:
    $ref: './paths/mod/project-report.yaml'
  /api/mod/bug-report/{id}:
    $ref: './paths/mod/bug-report-id.yaml'
  /api/mod/bug-report/:
    $ref: './paths/mod/bug-report.yaml'
  /api/mod/user-report/:
    $ref: './paths/mod/user-report.yaml'
  /api/mod/project-report/:
    $ref: './paths/mod/project-report.yaml'
  /api/mod/unban-user/{id}:
    $ref: './paths/mod/unban-user.yaml'
  /api/mod/notification:
    $ref: './paths/mod/notification.yaml'
  /api/mod/ban-user/{id}:
    $ref: './paths/mod/ban-user.yaml'
  /api/mod/delete-project/{id}:
    $ref: './paths/mod/delete-project.yaml'
  /api/mod/user-report/{id}/deactivate:
    $ref: './paths/mod/user-report-deactivate.yaml'
  /api/mod/clear-profile/{id}:
    $ref: './paths/mod/clear-profile.yaml'

  # PROJECTS
  /api/projects:
    $ref: './paths/projects/projects.yaml'
  /api/projects/paginated/{count}/{id}/{method}:
    $ref: './paths/projects/paginated.yaml'
  /api/projects/{id}:
    $ref: './paths/projects/projects-id.yaml'
  /api/projects/{id}/socials:
    $ref: './paths/projects/socials.yaml'
  /api/projects/{id}/socials/{socialId}:
    $ref: './paths/projects/socialId.yaml'
  /api/projects/{id}/tags:
    $ref: './paths/projects/tags.yaml'
  /api/projects/{id}/tags/{tagId}:
    $ref: './paths/projects/tagId.yaml'
  /api/projects/{id}/mediums:
    $ref: './paths/projects/mediums.yaml'
  /api/projects/{id}/mediums/{mediumId}:
    $ref: './paths/projects/mediumId.yaml'
  /api/projects/{id}/jobs:
    $ref: './paths/projects/jobs.yaml'
  /api/projects/{id}/jobs/{jobId}:
    $ref: './paths/projects/jobId.yaml'
  /api/projects/{id}/followers:
    $ref: './paths/projects/followers.yaml'
  /api/projects/{id}/visibility:
    $ref: './paths/projects/visibility.yaml'

  # MEDIA
  /api/projects/{id}/thumbnail:
    $ref: './paths/projects/media/thumbnail.yaml'
  /api/projects/{id}/images:
    $ref: './paths/projects/media/images.yaml'
  /api/projects/{id}/images/{imageId}:
    $ref: './paths/projects/media/imageId.yaml'
  /api/projects/{id}/images/reorder:
    $ref: './paths/projects/media/reorder-images.yaml'
  /api/projects/{id}/videos:
    $ref: './paths/projects/media/videos.yaml'
  /api/projects/{id}/videos/{videoId}:
    $ref: './paths/projects/media/videoId.yaml'

  # MEMBERS
  /api/projects/{id}/members:
    $ref: './paths/projects/members/members.yaml'
  /api/projects/{id}/members/send-invite:
    $ref: './paths/projects/members/send-invite.yaml'
  /api/projects/{id}/members/request-to-join:
    $ref: './paths/projects/members/request-join.yaml'
  /api/projects/{id}/members/applications:
    $ref: './paths/projects/members/applications.yaml'
  /api/projects/members/invitations:
    $ref: './paths/projects/members/invitations.yaml'
  /api/projects/members/requests:
    $ref: './paths/projects/members/member-request.yaml'
  /api/projects/members/requests/{id}:
    $ref: './paths/projects/members/member-request-id.yaml'
  /api/projects/{id}/members/{userId}:
    $ref: './paths/projects/members/membersId.yaml'
  /api/projects/{id}/change-owner/{userId}:
    $ref: './paths/projects/members/change-owner.yaml'
  /api/projects/{id}/members/{userId}/invite:
    $ref: './paths/projects/members/member-invite.yaml'

  # APPROVAL
  /api/projects/unapproved:
    $ref: './paths/projects/approval/unapproved.yaml'
  /api/projects/unapproved/{id}:
    $ref: './paths/projects/approval/unapproved-id.yaml'
  /api/projects/{id}/approve:
    $ref: './paths/projects/approval/approve.yaml'
  /api/projects/{id}/unapprove:
    $ref: './paths/projects/approval/unapprove.yaml'

  # USERS
  /api/users/all/{method}:
    $ref: './paths/users/get-all.yaml'
  /api/users:
    $ref: './paths/users/create.yaml'
  /api/users/{id}:
    $ref: './paths/users/get-id.yaml'
  /api/users/search-username/{username}:
    $ref: './paths/users/search-username.yaml'
  /api/users/search-email/{email}:
    $ref: './paths/users/search-email.yaml'
  /api/users/search-google/{id}:
    $ref: './paths/users/search-google.yaml'
  /api/users/{id}/projects:
    $ref: './paths/users/projects.yaml'
  /api/users/{id}/followings/projects:
    $ref: './paths/users/followings-projects.yaml'
  /api/users/{id}/followings/people:
    $ref: './paths/users/followings-people.yaml'
  /api/users/{id}/followers:
    $ref: './paths/users/followers.yaml'
  /api/users/blacklist:
    $ref: './paths/users/blacklist.yaml'
  /api/users/blacklist/{id}:
    $ref: './paths/users/blacklist-id.yaml'

# COMPONENTS
components:
  securitySchemes:
    shibbolethAuth:
      #Filler values need to be changed
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Role:
      $ref: 'schemas/datasets.yaml#/components/schemas/Role'
    Major:
      $ref: 'schemas/datasets.yaml#/components/schemas/Major'
    Tag:
      $ref: 'schemas/datasets.yaml#/components/schemas/Tag'
    Social:
      $ref: 'schemas/datasets.yaml#/components/schemas/Social'
    Skill:
      $ref: 'schemas/datasets.yaml#/components/schemas/Skill'
    Medium:
      $ref: 'schemas/datasets.yaml#/components/schemas/Medium'

    UserMember:
      $ref: 'schemas/users.yaml#/components/schemas/UserMember'
    UserSkill:
      $ref: 'schemas/users.yaml#/components/schemas/UserSkill'
    UserSocial:
      $ref: 'schemas/users.yaml#/components/schemas/UserSocial'
    ProjectFollowsList:
      $ref: 'schemas/users.yaml#/components/schemas/ProjectFollowsList'
    ProjectFollowing:
      $ref: 'schemas/users.yaml#/components/schemas/ProjectFollowing'
    UserFollowsList:
      $ref: 'schemas/users.yaml#/components/schemas/UserFollowsList'
    UserFollowing:
      $ref: 'schemas/users.yaml#/components/schemas/UserFollowing'
    UserPreview:
      $ref: 'schemas/users.yaml#/components/schemas/UserPreview'
    UserDetail:
      $ref: 'schemas/users.yaml#/components/schemas/UserDetail'
    BanDetail:
      $ref: 'schemas/users.yaml#/components/schemas/BanDetail'
    UserReport:
      $ref: 'schemas/users.yaml#/components/schemas/UserReport'
    BugReport:
      $ref: 'schemas/users.yaml#/components/schemas/BugReport'

    MySkill:
      $ref: 'schemas/me.yaml#/components/schemas/MySkill'
    MySocial:
      $ref: 'schemas/me.yaml#/components/schemas/MySocial'
    MyMajor:
      $ref: 'schemas/me.yaml#/components/schemas/MyMajor'
    MyFollowing:
      $ref: 'schemas/me.yaml#/components/schemas/MyFollowing'
    MyFollowsList:
      $ref: 'schemas/me.yaml#/components/schemas/MyFollowsList'
    MyProjectFollowing:
      $ref: 'schemas/me.yaml#/components/schemas/MyProjectFollowing'
    MyProjectFollowsList:
      $ref: 'schemas/me.yaml#/components/schemas/MyProjectFollowsList'
    MePreview:
      $ref: 'schemas/me.yaml#/components/schemas/MePreview'
    MeDetail:
      $ref: 'schemas/me.yaml#/components/schemas/MeDetail'
    MePrivate:
      $ref: 'schemas/me.yaml#/components/schemas/MePrivate'
    MyMember:
      $ref: 'schemas/me.yaml#/components/schemas/MyMember'

    ProjectImage:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectImage'
    ProjectMedium:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectMedium'
    ProjectFollowers:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectFollowers'
    ProjectFollower:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectFollower'
    ProjectMember:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectMember'
    ProjectMemberRequest:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectMemberRequest'
    ProjectSocial:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectSocial'
    ProjectTag:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectTag'
    ProjectJob:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectJob'
    ProjectPreview:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectPreview'
    ProjectDetail:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectDetail'
    ProjectWithFollowers:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectWithFollowers'
    ProjectVideo:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectVideo'
    ProjectReport:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectReport'

    UpdateUserInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateUserInput'
    AddUserSocialInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddUserSocialInput'
    UpdateUserSocialInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateUserSocialInput'
    AddUserSkillsInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddUserSkillsInput'
    UpdateUserSkillInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateUserSkillInput'
    AddUserMajorInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddUserMajorInput'
    CreateProjectInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectInput'
    UpdateProjectInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectInput'
    CreateProjectImageInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectImageInput'
    UpdateProjectImageInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectImageInput'
    ReorderProjectImagesInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/ReorderProjectImagesInput'
    CreateProjectMemberInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectMemberInput'
    UpdateProjectMemberInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectMemberInput'
    AddProjectSocialInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddProjectSocialInput'
    UpdateProjectSocialInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectSocialInput'
    AddProjectTagInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddProjectTagInput'
    UpdateProjectTagInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectTagInput'
    AddProjectMediumsInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddProjectMediumsInput'
    CreateProjectJobInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectJobInput'
    UpdateProjectJobInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectJobInput'
    CreateProjectVideoInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectVideoInput'
    CreateMemberRequestInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateMemberRequestInput'
    TagWithIdInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/TagWithIdInput'
    TagInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/TagInput'
    SkillInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/SkillInput'
    AddUserReportInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddUserReportInput'
    AddProjectReportInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddProjectReportInput'
    BanUserInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/BanUserInput'
    ModeratorNotificationInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/ModeratorNotificationInput'
    AddBugReportInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddBugReportInput'
    UpdateBugReportInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateBugReportInput'

    ErrorMessage:
      type: object
      properties:
        status:
          type: integer
          example: 500
        error:
          type: string
          example: Internal Server Error
        data:
          type: string
          nullable: true
          example: null
      required:
        - status
        - error
        - data

  responses:
    InternalServerError:
      description: An internal server error occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 500
                error: Internal Server Error
                data: null
    BadRequest:
      description: The request was invalid (e.g., malformed parameters)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 400
                error: Invalid parameter(s)
                data: null
    NotFound:
      description: The requested resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 404
                error: Not found
                data: null
    Unauthorized:
      description: Authentication is required and has failed or has not been provided
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 401
                error: Unauthorized
                data: null
    Forbidden:
      description: Proper credentials have been provided, but such credentials are not authorized to access this resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 409
                error: Forbidden
                data: null
    Conflict:
      description: Conflict to show resource already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 409
                error: Resource already exists
                data: null
