name: Build client

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'client/**'
      - '.github/workflows/build-client.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20.18.2'

      - name: Install dependencies
        run: npm ci

      - name: Build client
        run: npm run build:client
