name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - "Dockerfile"
      - ".github/workflows/deploy-server.yaml"
  pull_request:
    branches:
      - backend-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ghcr.io/lookingforgrp-rit/lfg-server:latest
