name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - "Dockerfile"
      - "containers/services/server/lfg-backend.container"
      - ".github/workflows/deploy-server.yaml"

jobs:
  build-server-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/lookingforgrp-rit/lfg-server:latest
            ghcr.io/lookingforgrp-rit/lfg-server:${{github.run_number}}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            build.number=${{ github.run_number }}

  deploy-server-image:
    needs: build-server-image
    runs-on: ubuntu-latest
