name: Test Server

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "server/**"
      - ".github/workflows/test-server.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ">=v23.6.0"

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Lint Types
        run: npm run lint:server:types

      - name: Lint Code
        run: npm run lint:server

      # Commented out as we don't have server side tests for services implemented yet
      # - name: Generate Prisma Client
      #   run: npm run prisma:generate

      # - name: Start Docker Compose Services
      #   run: npm run compose:up

      # - name: Run Tests
      #   run: npm run test:server
