name: Test Server

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "server/**"
      - ".github/workflows/test-server.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ">=v23.6.0"

      - name: Install dependencies
        run: npm ci --workspace=server --ignore-scripts

      - name: Generate Prisma
        run: npm run prisma:generate

      - name: Typecheck project
        run: npm run lint:server:types

      - name: Lint project
        run: npm run lint:server

      # Uncomment or change when we have db mocking
      # a db running in the workflow
      # or just chsnge tests to not use the db
      # - name: Test Server
        # run: npm run test