name: Test Client

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "client/**"
      - ".github/workflows/build-client.yml"

jobs:
  test-client:
    runs-on: ubuntu-latest
    environment: Testing
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ">=v23.6.0"

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      # - name: Lint Types
      #   run: npm run lint:client:types

      # - name: Lint Code
      #   run: npm run lint:client

      - name: Generate Prisma Client
        run: npm run prisma:generate

      - name: Start Docker Compose Services
        run: npm run compose:up

      - name: Give Compose Services Time to Start
        run: sleep 10

      - name: Run Tests
        run: npm run test:client

      - name: Build Client
        run: npm run build:client
